---
  - name: Copy logstash package to tmp directory
    copy:
        src: /home/zaloni/zdprpms/{{item}}
        dest: /tmp/zdp_install_temp_dir
    with_items:
        - "zdp-logstash-5.4.0.0-1.noarch.rpm"

#  - name: Install logstash in server from local yum repository
#    yum:
#        name: "{{item}}"
#        enablerepo: "{{zdp_yum_repository_name}}"
#        skip_broken: yes
#    with_items:
#        - "zdp-logstash"

  - name: Install logstash in server from local RPM
    yum:
        name: "/tmp/zdp_install_temp_dir/{{item}}"
        state: present
    with_items:
        - "zdp-logstash-5.4.0.0-1.noarch.rpm"

  - name: Configure with Registry
    become: True
    yedit:
        src: /etc/zdp-logstash/zdp-logstash.yml
        key: zdp.registry.password
        value: "{{registry_admin_password}}"

  - name: Configure with Registry
    become: True
    yedit:
        src: /etc/zdp-logstash/zdp-logstash.yml
        key: zdp.registry.config.url
        value: "http://{{ groups['registry']|join(',') }}:8761/config/master/application"

