---

# This is a sample Inventory file for the ZDP Installer Ansible Playbooks
# The topology (what service goes where is setup here.)
# Variables specific to an installation go to vars.yml. Secrets go to vault.yml

# Don't forget the the ':' at the end of each hostname
all:
  children:
    mysql:
      hosts:
        sandbox-hdp:
    node:
      hosts:
        sandbox-hdp:
    registry:
      hosts:
        sandbox-hdp:
    gateway:
      hosts:
        sandbox-hdp:
    ingestion-warden:
      hosts:
        sandbox-hdp:
    executor:
      hosts:
        sandbox-hdp:
    hive:
      hosts:
        sandbox-hdp:
    mr:
      hosts:
        sandbox-hdp:
    spark:
      hosts:
        sandbox-hdp:
    lineage:
      hosts:
        sandbox-hdp:
    es:
      hosts:
        sandbox-hdp:
    logstash:
      hosts:
        sandbox-hdp:
    kibana:
      hosts:
        sandbox-hdp:
    activemq:
      hosts:
        sandbox-hdp:
    hdpvm:
      hosts:
        40.118.71.52:
