# Create or update a template deployment based on uris using parameter and template links
- name: Deploy Hortonworks Template
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Deploy Hortonworks Template
      azure_rm_deployment:
        deployment_name: "zdpLabDeployment"
        location: westeurope
        state: present
        resource_group_name: zdptraining
        parameters_link: 'https://raw.githubusercontent.com/faisalzafaruae/zdp50labs/master/azure-templates/parameters.json'
        template_link:   'https://raw.githubusercontent.com/faisalzafaruae/zdp50labs/master/azure-templates/zdptemplate.json'
