# Create or update a template deployment based on uris using parameter and template links
- name: Install pexpect
  hosts: "137.117.178.235:"
  become: yes
  become_user: root
  vars:
    ansible_user: zaloni
    ansible_sudo_pass: Dubai@202092
  tasks:
    - name:  easy_install pexpect
      shell:  easy_install pexpect
      register: easyinstalltext
    - debug:
         msg: "Key Value: {{ easyinstalltext.stdout }}"
    #- command: "python -c 'import pexpect'"

- name: Reseting Root Password
  hosts: "137.117.178.235:"
  #gather_facts: False
#  user: "{{ hdpvm_admin_username }}"
  vars:
    ansible_user: zaloni
    ##ansible_ssh_pass: Dubai@202092
    ansible_sudo_pass: Dubai@202092
  tasks:
    - name: Try to reset root password 
      expect:
         command: sshpass -v -p "hadoop" ssh root@172.17.0.2 -o StrictHostKeyChecking=no 
         responses: 
           UNIX password: "hadoop"
           New password: "Dubai@202092"
           Retype new password: "Dubai@202092"
           -hdp ~]#: "exit"
