# Create or update a template deployment based on uris using parameter and template links
- name: Wait for SSH and then print hostname
  hosts: "40.118.71.52:"
  #gather_facts: False
#  user: "{{ hdpvm_admin_username }}"
  vars:
    ansible_user: zaloni
    ##ansible_ssh_pass: Dubai@202092
    ansible_sudo_pass: Dubai@202092
  tasks:

    - name: install pexpect
      pip:
         name: pexpect
      become: yes

    - name: Try to reset root password 
      expect:
         command: sshpass -v -p "hadoop" ssh root@172.17.0.2 -o StrictHostKeyChecking=no 
         responses: 
           UNIX password: "hadoop"
           New password: "Dubai@202092"
           Retype new password: "Dubai@202092"