# Create or update a template deployment based on uris using parameter and template links


- name: Clone GIT Repo on the Gateway machine
  hosts: "137.117.178.235:"
  vars:
      ansible_user: "{{ hdpvm_admin_username }}"
  tasks:
    - stat: path="~/zdp50labs/README.md"
      register: zdpinstallpath
    - name: Clone GIT Repo for ZDP Installation 
      expect:
         command: git clone https://zalonidxb@gitlab.com/jitulnath/zdp-ansible.git
         responses: 
           zalonidxb@gitlab.com': Zaloni@202092
      when: zdpinstallpath.stat.exists == false
