# Create or update a template deployment based on uris using parameter and template links
- name: Deploying Cloud Infrastructure
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Deploy Hortonworks Template
      azure_rm_deployment:
        deployment_name: "zdpLabDeployment"
        location: westeurope
        state: present
        resource_group_name: zdptraining
        template_link:   'https://raw.githubusercontent.com/faisalzafaruae/zdp50labs/master/azure-templates/zdptemplate.json'
        parameters: 
          location: 
            value: "westeurope"
          resourceGroup:
            value: "zdptraining"
          virtualMachineName:
            value: "zdp-gateway"        
          virtualMachineSize:
            value: "Standard_DS13-4_v2"
          adminUsername: 
            value: "zaloni"
          virtualNetworkName: 
            value: "ZDP50Demo-vnet"
          networkInterfaceName:
            value: "zdp-50222"
          networkSecurityGroupName:
            value: "ZDP-50-nsg"
          adminPassword:
            value: "Dubai@202092"
          diagnosticsStorageAccountName:
            value: "zdiag"
          diagnosticsStorageAccountType:
            value: "Standard_LRS"
          diagnosticsStorageAccountId:
            value: "Microsoft.Storage/storageAccounts/zdp50demodiag297"
          addressPrefix: 
            value: "10.0.1.0/24"
          subnetName: 
            value: "default"
          subnetPrefix:
            value: "10.0.1.0/24"
          publicIpAddressName: 
            value: "ZDP-50-ip"
          publicIpAddressType:
            value: "Static"
          publicIpAddressSku:
            value: "Basic"
      
