---
#  - name: Copy node package to tmp directory
#    copy:
#        src: /tmp/zdp_rpm_packages/{{item}}
#        dest: "{{zdp_package_temp_location}}"
#    with_items:
#        - "node-v6.14.3-linux-x64.tar.gz"

#  - name: Untar node package to /opt
#    unarchive:
#       src: "{{zdp_package_temp_location}}/node-v6.14.3-linux-x64.tar.gz"
#       dest: /opt

  - name: Install npm and nodejs in server from local yum repository
    yum:
        name: "{{item}}"
        enablerepo: "{{zdp_yum_repository_name}}"
        skip_broken: yes
    with_items:
        - "npm"
        - "nodejs"
