---
  - name: Copy node package to tmp directory
    copy:
        src: /home/zaloni/zdprpms/{{item}}
        dest: /home/zaloni/zdprpms/
    with_items:
        - "node-v6.9.5-linux-x64.tar.gz"

  - name: Untar node package to /opt
    unarchive:
       src: "/home/zaloni/zdprpms/node-v6.9.5-linux-x64.tar.gz"
       dest: /opt

#  - name: Install npm and nodejs in server from local yum repository
#    yum:
#        name: "{{item}}"
#        enablerepo: "{{zdp_yum_repository_name}}"
#        skip_broken: yes
#    with_items:
#        - "npm"
#        - "nodejs"
