---
#  - name: Copy lineage package to tmp directory
#    copy:
#        src: /tmp/zdp_rpm_packages/{{item}}
#        dest: /tmp/zdp_install_temp_dir
#    with_items:
#        - "zdp-lineage-5.0.0_FINAL.0-1.noarch.rpm"

  - name: Install lineage in server from local yum repository
    yum:
        name: "{{item}}"
        enablerepo: "{{zdp_yum_repository_name}}"
        skip_broken: yes
    with_items:
        - "zdp-lineage"


  - name: Configure with Registry
    become: True
    yedit:
        src: /etc/zdp-lineage/bootstrap-prod.yml
        key: jhipster.registry.password
        value: "{{registry_admin_password}}"

  - name: Configure with Registry
    become: True
    yedit:
        src: /etc/zdp-lineage/bootstrap-prod.yml
        key: spring.cloud.config.uri
        value: "http://admin:${jhipster.registry.password}@{{ groups['registry']|join(',') }}:8761/config"

  - name: Configure with Registry
    become: True
    yedit:
        src: /etc/zdp-lineage/zdp-lineage.yml
        key: eureka.instance.service-url.defaultZone
        value: "http://admin:${jhipster.registry.password}@{{ groups['registry']|join(',') }}:8761/eureka/"


# Execute if zdp_ssl_enable is set to True
  - name: Set JAVA_OPTS parameters
    lineinfile:
        path: /etc/sysconfig/zdp-lineage
        line: "JAVA_OPTS=\"-Djavax.net.ssl.trustStore={{ zdp_ssl_trust_store }} -Djavax.net.ssl.trustStoreType={{ zdp_ssl_key_store_type }} -Djavax.net.ssl.trustStorePassword={{ zdp_ssl_key_store_password }} -Djavax.net.debug=ssl\""
    when: zdp_ssl_enable == True
